### ISSUE TITLE
Set up & default to HTTPS

### ISSUE THREAD

**Issue by edunham** [servo/download.servo.org#1]

**Comment by OmgImAlexis** [comment]
HSTS would be the best option here as you can have all subdomains of servo.org be set to force https by default without it needing to be per subdomain. I'd also suggest adding the whole domain to the HSTS preload list, since this project is supported by Mozilla it should be even easier to be added to that.

Since you seem to be using Cloudflare infront of a S3 bucket you should be able to setup [HSTS in Cloudflare](https://blog.cloudflare.com/enforce-web-policy-with-hypertext-strict-transport-security-hsts/).

**Comment by edunham** [comment]
@OmgImAlexis Thanks for the feedback! Flipping the HSTS switch for all of servo.org would be problematic right now because we haven't SSL'd the buildbot and Homu interfaces yet, but I've set the download pages to automatically redirect HTTP traffic to HTTPS. 

I'm going to close this issue for now and keep track of progress on HSTS in https://github.com/servo/saltfs/issues/423.

**Comment by aneeshusa** [comment]
This works on download.servo.org, but not on dl.servo.org.
