### ISSUE TITLE
All download links are broken

### ISSUE THREAD

**Issue by jdm** [servo/download.servo.org#73]
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>08EBA35938DF3C85</RequestId>
<HostId>
fxjYErHRgxxhmtolSP2jEuZnXLAE7oVR/vlZbHgNbstOFvx7lSXJx12UrK10s8MXE6TEprDpW5I=
</HostId>
</Error>
```

@SimonSapin Are the ACLs incorrect somehow?

**Comment by jdm** [comment]
Apparently there's a `x-cache: Error from cloudfront` header as well.

**Comment by ryanc-me** [comment]
@jdm Yeah, that's what I'm getting from curl:

```
$ curl -Is https://download.servo.org/nightly/windows-msvc/servo-latest.exe
HTTP/2 403
content-type: application/xml
date: Mon, 16 Nov 2020 03:44:32 GMT
server: AmazonS3
x-cache: Error from cloudfront
via: 1.1 703d8189eecba19920d4f049a6c8c1c3.cloudfront.net (CloudFront)
x-amz-cf-pop: LAX50-C3
x-amz-cf-id: Cf8q7k-goDv131OW9x4vOd-0r_ZbnWYzh1uDbkslEoq9LgR8n4_dwQ==
```

For what it's worth, FontAwesome had a [similar-ish issue a few weeks ago](https://github.com/FortAwesome/Font-Awesome/issues/17346#issuecomment-720597803). Not sure what eventually solved it, but it sounds like it was an ACL/cache problem.

**Comment by SimonSapin** [comment]
This was an S3 permission configuration issue since moving to a new bucket (https://github.com/servo/download.servo.org/pull/72) and should be fixed now. I’ve copied the policy from the old bucket that gives read permission for everything to everyone. When migrating I had set an ACL to every object but that doesn’t affect objects added later such as new Nightlies.

```
$ curl -Is https://download.servo.org/nightly/windows-msvc/servo-latest.exe | head -n3
HTTP/2 200 
content-type: binary/octet-stream
content-length: 92117661
```
